version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.01.2
      docker_layer_caching: true
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
workflows:
  basic:
    jobs:
      - build-and-test